[package]
name = "holochain-serialization"
version = "0.1.0"
edition = "2021"

[lib]
name = "holochain_serialization"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.19.0"
holo_hash = "0.2.6"
holochain_zome_types = "0.2.6"
